//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskControll
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXDPlan
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string responsible { get; set; }
        public System.DateTime date { get; set; }
        public string executor { get; set; }
        public string department { get; set; }
        public string report { get; set; }
        public byte[] reportfile { get; set; }
        public Nullable<int> status { get; set; }
    }
}
